### ISSUE TITLE
feat: Improve WalterConfig

### ISSUE THREAD

**Issue by jwallace145** [jwallace145/walter-backend#178]
Walter uses a `config.yaml` to configure itself, right now it essentially just picks the model to use for Bedrock API calls, but it can be so much more.

Here's how it looks currently:

```yaml
walter_config:
  model_id: "Amazon: Nova Micro" # the least expensive model with sufficient input token size https://aws.amazon.com/bedrock/pricing/ (2025-02-10)
  temperature: 0.5
  top_p: 0.9
  generate_responses: true
  newsletter_template: "default"
  send_newsletter: true
  dump_newsletter: false
  emit_metrics: true
  jwt_algorithm: "HS256"
```

This should be updated so that useless config keys are not present, separate YAML sections for various functionality (Bedrock configs, News Summary configs, Newsletter configs). 

I want admins for Walter to be able to highly-configure Walter with just this file and check it in/out of source code so that manipulating the available levers is incredibly easy 🚀
